#!/usr/bin/env python3
"""Rasterize native/packaging/sstvae.svg into the shipped icon formats.

    tools/gen_icons.py

Four platforms want four containers and none of them wants an SVG:

    sstvae.ico          Windows -- linked into the .exe as a resource,
                        and used by the NSIS installer for its shortcuts
    sstvae.icns         macOS -- Contents/Resources, named by the
                        Info.plist's CFBundleIconFile
    icons/*.png         freedesktop -- hicolor/<size>x<size>/apps, which
                        is what a Linux menu, an AppImage's thumbnail and
                        a taskbar all read
    android res/        Android -- an *adaptive* icon, which is not one
                        image but two layers the launcher composites and
                        masks itself; see ANDROID_ below

The Android set is the one that is not simply "the same picture at
another size", so it is worth knowing what it is doing before changing
it.

Generated and committed, like config.hpp and the golden vectors, so that
a plain `cmake` build needs neither Python nor librsvg. Unlike those two
it is deliberately **not** a CI gate: the check would have to be a
byte-comparison of rasterized output, and librsvg's antialiasing is not
promised to be stable across versions, so the gate would fail on a
librsvg upgrade with no icon having changed. Re-run this by hand when
the SVG changes, and look at the result -- which is the only check that
means anything for an icon anyway.

Everything this writes is a derivative of the SVG, which is **licensed
artwork and not under the project's license** (see NOTICE). So each
output gets an SPDX sidecar written beside it here, rather than by hand:
adding a size later would otherwise put an unlabelled non-free file into
a repository whose root LICENSE says Artistic-2.0, and nothing would
notice.

Requires `rsvg-convert` (librsvg) and Pillow. Rasterizing every size
from the vector rather than downscaling one big PNG is the point: at 16
and 32 pixels a Lanczos reduction of a 1024px render is a grey blur,
where the renderer given a 16px viewport snaps the same shapes to the
pixel grid.
"""

from __future__ import annotations

import re
import shutil
import struct
import subprocess
import sys
from io import BytesIO
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SVG = ROOT / "native" / "packaging" / "sstvae.svg"
OUT = ROOT / "native" / "packaging"
ANDROID_RES = ROOT / "native" / "android-app" / "android" / "res"

# --- Android ---------------------------------------------------------------
#
# An adaptive icon is two layers, each 108dp square, of which the
# launcher guarantees only the central **72dp** is visible: it applies
# its own mask (circle, squircle, teardrop -- the user's choice, and the
# OEM's) and it animates the layers against each other on some
# launchers. So the artwork cannot be handed over as one flattened
# square, and a circular icon handed over as a foreground layer gets its
# edge clipped into a lens shape by any non-circular mask.
#
# Ours splits cleanly, which is luck worth using: sstvae.svg is a navy
# disc with the macaw drawn on top, so the disc becomes the background
# layer (a flat colour -- the mask is going to reshape it anyway) and
# the bird alone becomes the foreground.
#
# The bird is then scaled to sit inside the safe zone rather than the
# full layer. SAFE_FRACTION is against the 108dp layer: 72/108 is 0.667
# and is the guarantee, so anything at that exact value touches the mask
# edge on a circular launcher. 0.58 leaves the bird visibly inset, which
# is also how it reads on the desktop, where the disc gives it margin.
ANDROID_LAYER_DP = 108
ANDROID_LEGACY_DP = 48
ANDROID_SAFE_FRACTION = 0.58
# The standard buckets. mdpi is 1dp = 1px and everything else multiplies.
ANDROID_DENSITIES = (
    ("mdpi", 1.0),
    ("hdpi", 1.5),
    ("xhdpi", 2.0),
    ("xxhdpi", 3.0),
    ("xxxhdpi", 4.0),
)

# **The Android rasters cannot carry `.license` sidecars.** Anything
# under `res/` is fed to the Android resource merger, which rejects any
# file not named `*.xml` or `*.png` -- the build fails outright, which
# is at least loud. REUSE covers exactly this case with a coverage file
# listing paths, so the Android set is declared in
# native/android-app/REUSE.toml (outside `res/`, or it would be merged
# too) and written here for the same reason the sidecars are: adding a
# density later must not drop an unlabelled non-free file into a tree
# whose root LICENSE says Artistic-2.0.
REUSE_TOML = """\
# Generated by tools/gen_icons.py -- do not edit by hand.
#
# The launcher icon rasters are renderings of native/packaging/sstvae.svg,
# which is licensed artwork and NOT under the project's Artistic License
# 2.0; see NOTICE at the repository root. They are declared here rather
# than with `<file>.license` sidecars because the Android resource merger
# rejects any file under res/ that is not *.xml or *.png.
version = 1

[[annotations]]
path = [
{paths}]
SPDX-FileCopyrightText = "Licensed artwork, all rights reserved by its author"
SPDX-License-Identifier = "LicenseRef-SSTVAE-Branding"
"""

ADAPTIVE_XML = """\
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gen_icons.py. The layers are masked and animated
     by the launcher; see that script for why the bird is inset. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>
"""

# A hex triplet lifted from the artwork is not itself artwork, so this
# file gets no SPDX sidecar -- unlike every raster below, which is a
# rendering of the drawing and is restricted.
BACKGROUND_XML = """\
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/gen_icons.py from the disc in sstvae.svg. -->
<resources>
    <color name="ic_launcher_background">{color}</color>
</resources>
"""

# What each container needs. The union is rasterized once and shared.
PNG_SIZES = (16, 32, 48, 128, 256)
ICO_SIZES = (16, 24, 32, 48, 64, 128, 256)

# The icns element types, by the *pixel* size of their payload. Note that
# several sizes appear twice: `ic13` is "128 points at 2x" and `ic08` is
# "256 points at 1x", both 256 pixels, and macOS picks between them by
# the display's scale factor. Omitting the @2x forms is what makes an
# otherwise fine icon look soft on a Retina display.
ICNS_TYPES = (
    (b"icp4", 16),
    (b"icp5", 32),
    (b"ic11", 32),
    (b"ic12", 64),
    (b"ic07", 128),
    (b"ic13", 256),
    (b"ic08", 256),
    (b"ic14", 512),
    (b"ic09", 512),
    (b"ic10", 1024),
)


# The REUSE sidecar written beside every generated file. Kept in step
# with native/packaging/sstvae.svg.license, which is the hand-written one
# for the source artwork; if that changes, change this.
SIDECAR = """\
# The SSTVAE application icon is licensed artwork, NOT under the
# project's Artistic License 2.0. Rendered from
# native/packaging/sstvae.svg by tools/gen_icons.py; a derivative work,
# so the same restriction applies. See NOTICE at the repository root.
SPDX-FileCopyrightText: Licensed artwork, all rights reserved by its author
SPDX-License-Identifier: LicenseRef-SSTVAE-Branding
"""


def rasterize(size: int) -> Image.Image:
    """The SVG rendered at exactly `size` pixels square."""
    png = subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), str(SVG)],
        check=True,
        stdout=subprocess.PIPE,
    ).stdout
    image = Image.open(BytesIO(png)).convert("RGBA")
    if image.size != (size, size):  # librsvg honours -w/-h, but be sure
        raise SystemExit(f"gen_icons: rsvg-convert produced {image.size} for {size}")
    return image


def split_artwork() -> tuple[str, str]:
    """The SVG minus its background disc, and the disc's colour.

    Done by removing exactly one element and asserting it was there,
    rather than by pattern-matching whatever the file happens to
    contain: if the artwork is ever redrawn without a single flat disc
    behind it, the right outcome is a loud failure here and a human
    deciding what the two Android layers should be. A silent fallback
    would ship a foreground layer with a circle baked into it, which
    every non-circular launcher mask then clips into a lens.
    """
    svg = SVG.read_text()
    disc = re.search(
        r'\n?[ \t]*<circle[^>]*\bfill="(#[0-9A-Fa-f]{6})"[^>]*/>', svg
    )
    if disc is None:
        raise SystemExit(
            "gen_icons: no filled <circle> in sstvae.svg -- the Android "
            "adaptive icon needs the background separable from the "
            "subject; see ANDROID_ in this script."
        )
    foreground = svg[: disc.start()] + svg[disc.end() :]
    if "<circle" in foreground.split("</defs>")[-1]:
        raise SystemExit("gen_icons: more than one drawn circle; split by hand")
    return foreground, disc.group(1)


def rasterize_text(svg_text: str, size: int) -> Image.Image:
    """As `rasterize`, but from SVG source held in memory."""
    png = subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), "-"],
        check=True,
        input=svg_text.encode(),
        stdout=subprocess.PIPE,
    ).stdout
    return Image.open(BytesIO(png)).convert("RGBA")


def foreground_layer(bird: Image.Image, px: int) -> Image.Image:
    """The bird centred on a transparent `px` square, inside the safe zone.

    Rendered large and reduced *here* rather than rasterized at the
    target size, which is the opposite of the rule everywhere else in
    this file -- because the subject has to be measured before it can be
    placed. The SVG's viewBox is the disc, so the bird's own extent
    within it is not known until something has drawn it, and no `-w`
    given to rsvg-convert will centre a shape it has not been told the
    bounds of. The reduction is from a 4x render of the largest bucket,
    so the worst case is a 432px layer coming from 1728px.
    """
    box = bird.getbbox()
    if box is None:
        raise SystemExit("gen_icons: the foreground rendered empty")
    subject = bird.crop(box)
    target = int(round(px * ANDROID_SAFE_FRACTION))
    scale = target / max(subject.width, subject.height)
    fitted = subject.resize(
        (max(1, round(subject.width * scale)), max(1, round(subject.height * scale))),
        Image.LANCZOS,
    )
    layer = Image.new("RGBA", (px, px), (0, 0, 0, 0))
    layer.paste(fitted, ((px - fitted.width) // 2, (px - fitted.height) // 2), fitted)
    return layer


def write_android(images: dict[int, Image.Image]) -> list[Path]:
    """The adaptive icon, plus a legacy raster per density."""
    foreground_svg, background = split_artwork()
    # One big render, measured once and reduced per bucket.
    biggest = int(ANDROID_LAYER_DP * ANDROID_DENSITIES[-1][1]) * 4
    bird = rasterize_text(foreground_svg, biggest)

    written: list[Path] = []
    for name, factor in ANDROID_DENSITIES:
        d = ANDROID_RES / f"mipmap-{name}"
        d.mkdir(parents=True, exist_ok=True)

        fg = d / "ic_launcher_foreground.png"
        foreground_layer(bird, int(round(ANDROID_LAYER_DP * factor))).save(
            fg, "png", optimize=True
        )
        written.append(fg)

        # The legacy raster is the whole disc, unmasked, for anything
        # that asks for a plain icon rather than resolving the adaptive
        # XML. minSdk is 28 so no *device* needs it, but launchers,
        # share sheets and tooling read it, and a missing icon is a
        # worse failure than five small files.
        legacy = d / "ic_launcher.png"
        px = int(round(ANDROID_LEGACY_DP * factor))
        images.setdefault(px, rasterize(px))
        images[px].save(legacy, "png", optimize=True)
        written.append(legacy)

    anydpi = ANDROID_RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(ADAPTIVE_XML)

    values = ANDROID_RES / "values"
    values.mkdir(parents=True, exist_ok=True)
    (values / "ic_launcher_background.xml").write_text(
        BACKGROUND_XML.format(color=background)
    )

    toml = ANDROID_RES.parent.parent / "REUSE.toml"
    rel = sorted(p.relative_to(toml.parent).as_posix() for p in written)
    toml.write_text(REUSE_TOML.format(paths="".join(f'    "{r}",\n' for r in rel)))
    print(f"{toml.relative_to(ROOT)} covering {len(rel)} files")
    # Returned empty: main() writes a sidecar per returned path, and
    # these are the files that cannot have one.
    return []


def write_icns(path: Path, images: dict[int, Image.Image]) -> None:
    """Assemble an .icns by hand, one PNG payload per element.

    Pillow can write .icns, but only from a single image -- it upscales
    whatever it is given to 1024 and derives the rest, so the small
    elements come out as blurred reductions of a blur. The container
    itself is trivial: a header, then (4-byte type, big-endian length
    *including* the 8-byte header, payload) repeated.
    """
    elements: list[tuple[bytes, bytes]] = []
    for kind, size in ICNS_TYPES:
        buf = BytesIO()
        images[size].save(buf, "png")
        elements.append((kind, buf.getvalue()))

    # A table of contents is optional, but it is what lets a reader index
    # the file without walking it, and Finder writes one.
    toc = b"".join(kind + struct.pack(">I", len(data) + 8) for kind, data in elements)
    body = struct.pack(">I", len(toc) + 8) + toc
    body = b"TOC " + body
    for kind, data in elements:
        body += kind + struct.pack(">I", len(data) + 8) + data
    path.write_bytes(b"icns" + struct.pack(">I", len(body) + 8) + body)


def main() -> int:
    if not SVG.is_file():
        raise SystemExit(f"gen_icons: no source at {SVG}")
    if shutil.which("rsvg-convert") is None:
        raise SystemExit(
            "gen_icons: rsvg-convert not found (Debian/Ubuntu: librsvg2-bin, "
            "Arch: librsvg, macOS: brew install librsvg)"
        )

    sizes = sorted({*PNG_SIZES, *ICO_SIZES, *(s for _, s in ICNS_TYPES)})
    images = {size: rasterize(size) for size in sizes}

    png_dir = OUT / "icons"
    png_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for size in PNG_SIZES:
        path = png_dir / f"sstvae-{size}.png"
        images[size].save(path, "png", optimize=True)
        written.append(path)

    ico = OUT / "sstvae.ico"
    # `sizes` selects which frames to emit; `append_images` supplies the
    # natively rendered one for each, so nothing is downscaled here.
    images[max(ICO_SIZES)].save(
        ico,
        "ico",
        sizes=[(s, s) for s in ICO_SIZES],
        append_images=[images[s] for s in ICO_SIZES],
    )
    written.append(ico)

    icns = OUT / "sstvae.icns"
    write_icns(icns, images)
    written.append(icns)

    written += write_android(images)

    for path in written:
        sidecar = path.with_name(path.name + ".license")
        sidecar.write_text(SIDECAR)
        print(f"{path.relative_to(ROOT)} ({path.stat().st_size} bytes) + .license")
    return 0


if __name__ == "__main__":
    sys.exit(main())
